### PR TITLE
upgrade async_io

### PR DESCRIPTION
**Pull request by 0x8f701**

### CODE REVIEW

**Comment by vkill** [comment]
Hi, GopherJ

Thanks for your hard work, but this [example](https://github.com/bk-rs/async-ssh2-lite/blob/master/demos/smol/src/download_file.rs) not working for async-io 1.1.4 and higher.

I will try later.

**Comment by 0x8f701** [comment]
@vkill ok thanks I tried also to make a reverse tunnel but I didn't succeed yet

**Comment by vkill** [comment]
[With async-io 1.1.3](https://github.com/bk-rs/async-ssh2-lite/tree/async-io-1)

**Comment by vkill** [comment]
@GopherJ Please test [this](https://github.com/bk-rs/async-ssh2-lite/tree/async-io-1) branch, thank you.

**Comment by 0x8f701** [comment]
@vkill Hi, it works for me, I tried to edit a little bit the proxy_jump code to make a reverse tunnel, the tunnel works but just encountered a ICE error

https://github.com/rust-lang/rust/issues/80151

after cleaning cache it compiles finally.

thanks for your work!

**Pull request closed without merging**
